language: node_js

node_js:
  - "4.1.0"
  - "4.0.0"
  - "0.12.0"

before_install:
  - npm install
  - ./node_modules/.bin/bower install

script:
  - npm test  # In the future, this can be grunt or gulp commands

#services:
#  - mongodb
